In [6]:
from lib.metrics_set import distance_one
from tqdm import tqdm
import h5py
import glob

In [ ]:
import h5py
import glob

# Get a list of all .h5 files in the directory
h5_files = glob.glob('/data/DP/testing/*.h5')

# Load each .h5 file
h5_data = {}
for file in h5_files:
    with h5py.File(file, 'r') as f:
        h5_data[file] = {key: f[key][()] for key in f.keys()}


#排名分布
import numpy as np
a1 = []
a2 = []
a3 = []
a4 = []
for file, data in tqdm(h5_data.items()):
    temp_areas = []
    num_slices = data['label_a1'].shape[0]
    for one_slice in range(num_slices):
        temp_areas = [data['label_a1'][one_slice].sum(), data['label_a2'][one_slice].sum(), data['label_a3'][one_slice].sum(), data['label_a4'][one_slice].sum()]
        ranks = [np.argsort(temp_areas).tolist().index(i) + 1 for i in range(4)]
        a1.append(ranks[0])
        a2.append(ranks[1])
        a3.append(ranks[2])
        a4.append(ranks[3])

import matplotlib.pyplot as plt

# 设置图形大小
plt.figure(figsize=(20, 5))

# 绘制 a1 的直方图
plt.subplot(1, 4, 1)
plt.hist(a1, bins=range(1, 6), alpha=0.7, label='a1', color='blue', edgecolor='black')
plt.legend(loc='upper right')
plt.title('Distribution of a1')
plt.xlabel('Rank')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)

# 绘制 a2 的直方图
plt.subplot(1, 4, 2)
plt.hist(a2, bins=range(1, 6), alpha=0.7, label='a2', color='green', edgecolor='black')
plt.legend(loc='upper right')
plt.title('Distribution of a2')
plt.xlabel('Rank')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)

# 绘制 a3 的直方图
plt.subplot(1, 4, 3)
plt.hist(a3, bins=range(1, 6), alpha=0.7, label='a3', color='red', edgecolor='black')
plt.legend(loc='upper right')
plt.title('Distribution of a3')
plt.xlabel('Rank')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)

# 绘制 a4 的直方图
plt.subplot(1, 4, 4)
plt.hist(a4, bins=range(1, 6), alpha=0.7, label='a4', color='purple', edgecolor='black')
plt.legend(loc='upper right')
plt.title('Distribution of a4')
plt.xlabel('Rank')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)

# 显示图形
plt.tight_layout()
#plt.show()
plt.savefig('vis/rank_dis_test.png')

#print(h5_data)

[[1.         0.32505846 0.23329011 0.20058336]
 [0.32505846 1.         0.34847531 0.33536647]
 [0.23329011 0.34847531 1.         0.2517738 ]
 [0.20058336 0.33536647 0.2517738  1.        ]]

In [ ]:
import h5py
import glob

# Get a list of all .h5 files in the directory
h5_files = glob.glob('/data/DP/training_2d/*.h5')

# Load each .h5 file
h5_data = {}
for file in h5_files:
    with h5py.File(file, 'r') as f:
        h5_data[file] = {key: f[key][()] for key in f.keys()}
        
#排名分布
import numpy as np
a1 = []
a2 = []
a3 = []
a4 = []
for file, data in tqdm(h5_data.items()):
    temp_areas = []
    num_slices = data['label_a1'].shape[0]
    for one_slice in range(num_slices):
        temp_areas = [data['label_a1'][one_slice].sum(), data['label_a2'][one_slice].sum(), data['label_a3'][one_slice].sum(), data['label_a4'][one_slice].sum()]
        ranks = [np.argsort(temp_areas).tolist().index(i) + 1 for i in range(4)]
        a1.append(ranks[0])
        a2.append(ranks[1])
        a3.append(ranks[2])
        a4.append(ranks[3])

import matplotlib.pyplot as plt

# 设置图形大小
plt.figure(figsize=(20, 5))

# 绘制 a1 的直方图
plt.subplot(1, 4, 1)
plt.hist(a1, bins=range(1, 6), alpha=0.7, label='a1', color='blue', edgecolor='black')
plt.legend(loc='upper right')
plt.title('Distribution of a1')
plt.xlabel('Rank')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)

# 绘制 a2 的直方图
plt.subplot(1, 4, 2)
plt.hist(a2, bins=range(1, 6), alpha=0.7, label='a2', color='green', edgecolor='black')
plt.legend(loc='upper right')
plt.title('Distribution of a2')
plt.xlabel('Rank')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)

# 绘制 a3 的直方图
plt.subplot(1, 4, 3)
plt.hist(a3, bins=range(1, 6), alpha=0.7, label='a3', color='red', edgecolor='black')
plt.legend(loc='upper right')
plt.title('Distribution of a3')
plt.xlabel('Rank')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)

# 绘制 a4 的直方图
plt.subplot(1, 4, 4)
plt.hist(a4, bins=range(1, 6), alpha=0.7, label='a4', color='purple', edgecolor='black')
plt.legend(loc='upper right')
plt.title('Distribution of a4')
plt.xlabel('Rank')
plt.ylabel('Frequency')
plt.grid(axis='y', alpha=0.75)

# 显示图形
plt.tight_layout()
#plt.show()
plt.savefig('vis/rank_dis_train.png')

In [7]:
import numpy as np
from joblib import Parallel, delayed
from tqdm import tqdm
import numpy as np
import glob
# Get a list of all .h5 files in the directory
h5_files = glob.glob('/data/DP/testing/*.h5')

# Load each .h5 file
h5_data = {}
for file in h5_files:
    with h5py.File(file, 'r') as f:
        h5_data[file] = {key: f[key][()] for key in f.keys()}


similar_matrix = np.ones((len(h5_files), 4, 4))
# 定义计算单个切片的相似矩阵
def compute_similarity(one_slice_id, data):
    temp_matrix = np.ones((4, 4))
    for i in range(4):
        for j in range(i + 1, 4):
            temp_matrix[i, j] = distance_one(data[f'label_a{i+1}'][one_slice_id].flatten(),
                                         data[f'label_a{j+1}'][one_slice_id].flatten())
            temp_matrix[j, i] = temp_matrix[i, j]  # 对称赋值
    return temp_matrix

# 初始化计数
count = 0

# 遍历 h5 文件
for file, data in h5_data.items():
    num_slices = data['label_a1'].shape[0]
    
    # 使用 joblib 并行计算所有切片的相似矩阵
    temp_similar_matrices = Parallel(n_jobs=-1)(
        delayed(compute_similarity)(one_slice_id, data) for one_slice_id in tqdm(range(num_slices))
    )

    # 计算均值并存储
    similar_matrix[count, :, :] = np.mean(temp_similar_matrices, axis=0)
    count += 1
np.save('vis/similar_matrix.npy', similar_matrix)

100%|██████████| 21/21 [00:00<00:00, 63.88it/s]
/tmp/ipykernel_2548033/3486055258.py:22: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
/tmp/ipykernel_2548033/3486055258.py:22: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
/tmp/ipykernel_2548033/3486055258.py:22: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
/tmp/ipykernel_2548033/3486055258.py:22: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extr

In [8]:
import numpy as np
similar_matrix = np.load('vis/similar_matrix.npy')
tt = similar_matrix.mean(0)
print(tt)

[[1.         0.66862463 0.66964558 0.63881902]
 [0.66862463 1.         0.64490568 0.66509441]
 [0.66964558 0.64490568 1.         0.66631542]
 [0.63881902 0.66509441 0.66631542 1.        ]]


In [17]:
tt

array([[1.        , 0.99325058, 0.9923329 , 0.99200583],
       [0.99325058, 1.        , 0.99348475, 0.99335366],
       [0.9923329 , 0.99348475, 1.        , 0.99251774],
       [0.99200583, 0.99335366, 0.99251774, 1.        ]])

In [18]:
tt_normalized = (tt - np.min(tt, axis=1, keepdims=True)) / (np.max(tt, axis=1, keepdims=True) - np.min(tt, axis=1, keepdims=True))
print(tt_normalized)


[[1.         0.15570741 0.04091327 0.        ]
 [0.         1.         0.03469465 0.01527246]
 [0.         0.1502331  1.         0.0241078 ]
 [0.         0.16860183 0.06403474 1.        ]]


In [ ]:
print((similar_matrix[0]-0.99)*100)

In [ ]:
data['label_a1'].shape